# Generated by Django 5.0.6 on 2024-05-27 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0002_alter_bookimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('BOOKED', 'reservado'), ('CHECKEDOUT', 'retirado'), ('RETURNED', 'devolvido'), ('CANCELED', 'cancelado'), ('EXPIRED', 'expirado')], default='BOOKED', max_length=50)),
                ('protocol', models.CharField(max_length=2000)),
                ('booking_date', models.DateTimeField()),
                ('estimated_checkout_date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='book.book')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='booking.booking')),
            ],
        ),
    ]
