# Generated by Django 5.0.6 on 2024-05-27 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nacionality', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inside_code', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=50)),
                ('publication_date', models.DateField()),
                ('edition_date', models.DateField(blank=True, null=True)),
                ('pages', models.PositiveIntegerField()),
                ('size', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('edition_number', models.CharField(default='N/A', max_length=50)),
                ('isbn', models.CharField(max_length=15)),
                ('authors', models.ManyToManyField(related_name='books', to='book.author')),
            ],
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='book_images/<django.db.models.fields.related.ForeignKey>/')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='book.book')),
            ],
        ),
    ]
