# Generated by Django 5.0.6 on 2024-05-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/%Y/%m/'),
        ),
        migrations.DeleteModel(
            name='BookImage',
        ),
    ]
